// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7Uaw0k2AgRLk5FxMco26OvVmT83iRdpY',
    appId: '1:309748043256:web:esp32tracker',
    messagingSenderId: '309748043256',
    projectId: 'esp32-tracker-86c05',
    authDomain: 'esp32-tracker-86c05.firebaseapp.com',
    storageBucket: 'esp32-tracker-86c05.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Uaw0k2AgRLk5FxMco26OvVmT83iRdpY',
    appId: '1:309748043256:android:d32516e66e5a34dd459a0d',
    messagingSenderId: '309748043256',
    projectId: 'esp32-tracker-86c05',
    storageBucket: 'esp32-tracker-86c05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Uaw0k2AgRLk5FxMco26OvVmT83iRdpY',
    appId: '1:309748043256:ios:d32516e66e5a34dd459a0d',
    messagingSenderId: '309748043256',
    projectId: 'esp32-tracker-86c05',
    storageBucket: 'esp32-tracker-86c05.firebasestorage.app',
    iosClientId: '309748043256-iosClientId.apps.googleusercontent.com',
    iosBundleId: 'com.example.esp32AlarmTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7Uaw0k2AgRLk5FxMco26OvVmT83iRdpY',
    appId: '1:309748043256:macos:d32516e66e5a34dd459a0d',
    messagingSenderId: '309748043256',
    projectId: 'esp32-tracker-86c05',
    storageBucket: 'esp32-tracker-86c05.firebasestorage.app',
    iosClientId: '309748043256-macosClientId.apps.googleusercontent.com',
    iosBundleId: 'com.example.esp32AlarmTrack',
  );
}
